try {
  xxxx += 1000;
} catch (e) {
  console.log('에러!');
  console.error(e);
} finally {
  console.log('finally!');
}
